UIOR-626 Clone PO does not clone Prefix and Suffix
folio-org/ui-orders pull request #997
Opened 2020-11-09 14:30 UTC by AndreiShumski2

## Purpose
https://issues.folio.org/browse/UIOR-626

## Approach
`poNumper` consists of `prefix`+`poNumber`+`suffix`
For cloning order, it requires to fetch the next poNumber from BE and then concatenate it with existing prefix and suffix

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2020-11-09 15:36 UTC, axelhunn commented on src/components/Utils/orderResource.js
> +  const poNumber = orderNumberResponse?.poNumber;
maybe throw here if `poNumber` is undefined?

2020-11-09 16:22 UTC, aliaksei-chumakou requested changes
There are separate fields for suffix and prefix, AFAIK https://github.com/folio-org/acq-models/blob/master/mod-orders-storage/schemas/purchase_order.json#L65

2020-11-09 18:38 UTC, aliaksei-chumakou commented on src/components/Utils/orderResource.js
> +  return poNumber ? saveOrder(clonedOrder, mutator) : Promise.reject();
this fn is written using asyn\await, IMO its better to use `throw` instead of `Promise`

2020-11-09 18:44 UTC, aliaksei-chumakou commented on src/components/Utils/orderResource.js
> +  return poNumber ? saveOrder(clonedOrder, mutator) : Promise.reject();
also throwing might be done earlier, near the place you've got poNumber

2020-11-10 08:12 UTC, AndreiShumski2 commented
> There are separate fields for suffix and prefix, AFAIK https://github.com/folio-org/acq-models/blob/master/mod-orders-storage/schemas/purchase_order.json#L65

[here](https://issues.folio.org/browse/UIOR-495) about creating and storing `poNumber` with suffixes and prefixes

2020-11-10 08:15 UTC, aliaksei-chumakou commented
IMHO, if number isnt provided - it's populated on the back-end and this should be a back-end fix to use prefix and suffix

2020-11-10 08:56 UTC, aliaksei-chumakou approved these changes

2020-11-10 09:27 UTC, axelhunn approved these changes

2020-11-10 09:43 UTC, merged